commerce_checkout.commerce_checkout_flow.*:
  type: config_entity
  label: 'Checkout flow'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: commerce_checkout.commerce_checkout_flow.plugin.[%parent.plugin]

commerce_checkout.commerce_checkout_flow.plugin.*:
  type: commerce_checkout_flow_configuration

commerce_checkout_flow_configuration:
  type: mapping
  mapping:
    id:
      type: string
      label: 'ID'
